.pragma library

// Colour. Omarchy gives five theme roles — foreground, background, accent, urgent,
// muted — and every bit of chrome uses them. The two non-chrome marks do not: the
// opencode brand mark is two literals, and the vendor marks are generated by rotating
// hues off Color.accent, so they follow every theme swap by construction.

// ---------------------------------------------------------------- luminance

function channelLum(c) {
  var v = c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
  return v
}

function hexRgb(hex) {
  var s = String(hex || "").replace("#", "")
  if (s.length === 3) s = s[0] + s[0] + s[1] + s[1] + s[2] + s[2]
  if (s.length < 6) return { r: 0, g: 0, b: 0 }
  return {
    r: parseInt(s.substr(0, 2), 16) / 255,
    g: parseInt(s.substr(2, 2), 16) / 255,
    b: parseInt(s.substr(4, 2), 16) / 255
  }
}

// Accepts a QML color (which has .r/.g/.b in 0..1) or a "#rrggbb" string, so
// callers can hand it a theme token or a literal without converting first.
function lumOf(c) {
  var rgb = (c && typeof c === "object" && c.r !== undefined) ? c : hexRgb(c)
  return 0.2126 * channelLum(rgb.r) + 0.7152 * channelLum(rgb.g) + 0.0722 * channelLum(rgb.b)
}

function contrast(a, b) {
  var la = lumOf(a), lb = lumOf(b)
  var hi = Math.max(la, lb), lo = Math.min(la, lb)
  return (hi + 0.05) / (lo + 0.05)
}

function isDarkSurface(c) { return lumOf(c) < 0.5 }

// ---------------------------------------------------------------- hsl

function toHsl(c) {
  var rgb = (c && typeof c === "object" && c.r !== undefined) ? c : hexRgb(c)
  var r = rgb.r, g = rgb.g, b = rgb.b
  var max = Math.max(r, g, b), min = Math.min(r, g, b)
  var l = (max + min) / 2, h = 0, s = 0
  if (max !== min) {
    var d = max - min
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0))
    else if (max === g) h = (b - r) / d + 2
    else h = (r - g) / d + 4
    h *= 60
  }
  return { h: h, s: s * 100, l: l * 100 }
}

function hslHex(h, s, l) {
  var hh = ((h % 360) + 360) % 360 / 360
  var ss = Math.max(0, Math.min(100, s)) / 100
  var ll = Math.max(0, Math.min(100, l)) / 100
  function hue2(p, q, t) {
    if (t < 0) t += 1
    if (t > 1) t -= 1
    if (t < 1 / 6) return p + (q - p) * 6 * t
    if (t < 1 / 2) return q
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6
    return p
  }
  var r, g, b
  if (ss === 0) { r = g = b = ll }
  else {
    var q = ll < 0.5 ? ll * (1 + ss) : ll + ss - ll * ss
    var p = 2 * ll - q
    r = hue2(p, q, hh + 1 / 3); g = hue2(p, q, hh); b = hue2(p, q, hh - 1 / 3)
  }
  function hx(v) {
    var n = Math.round(Math.max(0, Math.min(1, v)) * 255).toString(16)
    return n.length === 1 ? "0" + n : n
  }
  return "#" + hx(r) + hx(g) + hx(b)
}

// Lightness is solved, not assigned: HSL lightness is not luminance (a saturated
// green at L=44 is bright), so bisect for the L that hits the target on this surface.
function toneFor(h, s, surface, target) {
  var dark = isDarkSurface(surface)
  var lo = dark ? 20 : 4
  var hi = dark ? 96 : 70
  var best = dark ? hi : lo
  for (var i = 0; i < 22; i++) {
    var mid = (lo + hi) / 2
    var c = contrast(hslHex(h, s, mid), surface)
    best = mid
    if (c < target) { if (dark) lo = mid; else hi = mid }
    else { if (dark) hi = mid; else lo = mid }
  }
  return best
}

// ---------------------------------------------------------------- opencode

// opencode's own accent #9d7cd8 (accent of its default built-in "opencode" theme)
// clears neither end raw — 3.75:1 darkest, 2.94:1 lightest — and no single value
// clears both, so it ships in two lightnesses: 4.68:1 worst dark, 6.81:1 worst light.
var OPENCODE_ON_DARK = "#ad91de"
var OPENCODE_ON_LIGHT = "#6336b5"

function opencodeInk(surface) {
  return isDarkSurface(surface) ? OPENCODE_ON_DARK : OPENCODE_ON_LIGHT
}

// For callers that have already worked out which side they are on — the bar,
// where the surface is the wallpaper and only the shell knows.
function opencodeInkOn(dark) {
  return dark ? OPENCODE_ON_DARK : OPENCODE_ON_LIGHT
}

// ---------------------------------------------------------------- providers

var PROVIDER_SLOTS = {
  "anthropic": 0, "openai": 1, "google": 2, "openrouter": 3,
  "opencode": 4, "deepseek": 5, "xai": 6, "mistral": 7
}
var PROVIDER_STEP = 38
var PROVIDER_TARGET = 6.0

function providerSlot(id) {
  var k = String(id || "").toLowerCase()
  return PROVIDER_SLOTS.hasOwnProperty(k) ? PROVIDER_SLOTS[k] : -1
}

// Filled and hollow alternate so the marks stay separable without hue; tone as the
// second channel fails — a dimmer dot beside brighter text reads as disabled.
function providerFilled(id) {
  var s = providerSlot(id)
  return s >= 0 && s % 2 === 0
}

// No brand hexes: Google's guidelines forbid their colours in third-party UI, and a
// generated tint follows the theme for free.
function providerTint(providerId, accent, surface, fallback) {
  var slot = providerSlot(providerId)
  if (slot < 0) return fallback
  var base = toHsl(accent)
  // A theme whose accent is grey is saying it does not want hue. Eight of them
  // would be obnoxious rather than helpful.
  if (base.s < 12) return fallback
  var s = Math.max(45, Math.min(85, base.s))
  var h = base.h + slot * PROVIDER_STEP
  return hslHex(h, s, toneFor(h, s, surface, PROVIDER_TARGET))
}

// A profile has no `vendor` the way a template does — what a profile is, is the
// models in it — so the provider is counted rather than declared. It takes half the
// pinned rows to claim one: a profile spread evenly across three providers has no
// dominant provider, and says so instead of picking whichever came first.
function dominantProvider(rows) {
  if (!rows || !rows.length) return ""
  var count = {}, best = "", bestN = 0, total = 0
  for (var i = 0; i < rows.length; i++) {
    var m = rows[i] && rows[i].model
    if (!m) continue
    var p = String(m).split("/")[0]
    if (!p) continue
    count[p] = (count[p] || 0) + 1
    total++
    if (count[p] > bestN) { bestN = count[p]; best = p }
  }
  return (total > 0 && bestN * 2 >= total) ? best : ""
}

// ---------------------------------------------------------------- cost

// Weighted 1:4 in:out, which is roughly how agent traffic lands.
function blendedCost(model) {
  if (!model) return -1
  var i = Number(model.inputCost), o = Number(model.outputCost)
  if (!isFinite(i) || !isFinite(o)) return -1
  return i * 0.2 + o * 0.8
}

// The mean across the rows a profile pins, not its most common model: four Opus
// agents out of nineteen is not an Opus profile, and the bar should not say it is.
function profileCost(rows, index) {
  if (!rows || rows.length === 0) return -1
  var total = 0, n = 0
  for (var i = 0; i < rows.length; i++) {
    var m = index ? index[rows[i].model] : null
    var c = blendedCost(m)
    if (c < 0) continue
    total += c; n++
  }
  return n === 0 ? -1 : total / n
}

function costTier(c) {
  if (c < 0) return "unknown"
  if (c === 0) return "free"
  if (c < 5) return "light"
  if (c < 15) return "standard"
  return "top"
}

function profileTier(rows, index) { return costTier(profileCost(rows, index)) }

// Cost is ordinal: one hue at graded strength, not a categorical palette that would
// read as unrelated kinds. The caller composes the alpha through Util.alpha, since a
// .pragma library has no QML context to build a colour with.
function tierAlpha(tier) {
  if (tier === "free") return 0.30
  if (tier === "light") return 0.45
  return 0.65
}

// Whether the panel can vouch for a profile's cost at all: models the catalog has
// never heard of drop the dot rather than earn a confident low band.
function tierKnown(rows, index) {
  if (!rows || rows.length === 0) return false
  for (var i = 0; i < rows.length; i++) {
    if (index && index[rows[i].model]) return true
  }
  return false
}

// ---------------------------------------------------------------- mark

// opencode's own mark, as geometry rather than as a shipped bitmap. Taken from the
// project's brand asset: a 240x300 artboard, a uniform 60 border, and a cursor block
// filling the lower two thirds of the aperture. Kept as two separate paths on purpose
// — the brand draws them in two tones, and two tones is exactly one free channel.
var MARK_VIEW_W = 240
var MARK_VIEW_H = 300
var MARK_FRAME = "M240 300H0V0H240V300ZM180 60H60V240H180V60Z"

var MARK_APERTURE_X0 = 60
var MARK_APERTURE_X1 = 180
var MARK_APERTURE_Y0 = 60
var MARK_APERTURE_Y1 = 240

// The brand fills the lower two thirds of the aperture; this ships at two fifths.
// The block is the one thing that changes colour, and at two thirds it dominates a
// 16px mark badly enough that a switch reads as the whole icon changing rather than
// as a state moving. Two fifths still leaves ~4px of block on the bar, which is the
// floor for the cost bands to be separable at all — a quarter drops it to 2px and
// the grading disappears. Kept flush with the aperture's floor and sides: a block
// that floats free of them stops reading as a cursor and becomes a different logo.
var MARK_CURSOR_FILL = 2 / 5

function markCursorPath(fill) {
  var f = (fill === undefined) ? MARK_CURSOR_FILL : Math.max(0.05, Math.min(1, fill))
  var top = MARK_APERTURE_Y1 - (MARK_APERTURE_Y1 - MARK_APERTURE_Y0) * f
  return "M" + MARK_APERTURE_X1 + " " + MARK_APERTURE_Y1
    + "H" + MARK_APERTURE_X0
    + "V" + top
    + "H" + MARK_APERTURE_X1
    + "V" + MARK_APERTURE_Y1 + "Z"
}

// The cursor when the catalog cannot price the profile. Dimmer than the frame, the
// way the brand asset draws it, but deliberately outside the ordinal bands so it
// never reads as a confident cost claim.
function markNeutralAlpha() { return 0.55 }
